app {
  http {
    host = "0.0.0.0"
    port = 8080
  }

  subscription-number = "7997"

  phishing {
    api-base-url = "https://webrisk.googleapis.com"
    api-token = "dummy-token"
    cache-ttl-hours = 24
  }

  db {
    url = "jdbc:h2:file:./data/sms-phishing-filter;MODE=PostgreSQL;AUTO_SERVER=TRUE"
    driver = "org.h2.Driver"
    user = "sa"
    password = ""
  }
}
